on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Установка зависимостей
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip zip unzip openjdk-17-jdk libffi-dev \
            libssl-dev libncurses5 libncurses5-dev libsqlite3-dev zlib1g zlib1g-dev \
            libjpeg-dev libandroid-tools adb

          python3 -m pip install --upgrade pip
          pip install buildozer Cython

      - name: Сборка APK
        run: buildozer -v android debug

      - name: Проверка bin/
        run: ls -lah bin

      - name: Загрузка APK
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk
